### ISSUE TITLE
文字修正

### ISSUE THREAD

**Issue by Bearkern** [hexschool/bootstrap_zh#12]
https://github.com/hexschool/bootstrap_zh/blob/902bd06e6ba0bbf7621b9c5dc796bdb074aeb0c4/docs/4.0/components/modal/index.html#L1196

因「位」，應為因「為」

https://github.com/hexschool/bootstrap_zh/blob/902bd06e6ba0bbf7621b9c5dc796bdb074aeb0c4/docs/4.0/components/popovers/index.html#L1168

「校」能，應為「效」能

**Comment by Wcc723** [comment]
感謝，相關問題也一同修正了 :)
