### ISSUE TITLE
section-nav href target

### ISSUE THREAD

**Issue by gonsakon** [hexschool/bootstrap_zh#15]
右側錨點未更換為英文
![2018-01-25 00 34 55](https://user-images.githubusercontent.com/2187968/35344254-a49e3a58-0167-11e8-8238-ed7c6468677d.png)

**Comment by Wcc723** [comment]
![snip20180202_2](https://user-images.githubusercontent.com/3422575/35714418-76a582cc-0807-11e8-9589-1f534b98fcdb.png)

使用 JavaScript 修正
