### ISSUE TITLE
錯字修正

### ISSUE THREAD

**Issue by Wcc723** [hexschool/bootstrap_zh#16]
![image](https://user-images.githubusercontent.com/3422575/37248504-e83a2f72-250e-11e8-890b-7c7a2ff47e97.png)

**Comment by Jackson45252** [comment]
多打了一個 4
<img width="774" alt="2018-05-26 9 29 25" src="https://user-images.githubusercontent.com/9023148/40576623-33480a44-612c-11e8-8a8d-b90c081a8d90.png">

**Comment by Wcc723** [comment]
![image](https://user-images.githubusercontent.com/3422575/42487205-83d5a768-8432-11e8-8d56-4a7feed23daa.png)
下一版統一更新
