### ISSUE TITLE
英文版的文字排版中反轉排版 .blockquote-reverse 已經移掉了

### ISSUE THREAD

**Issue by kevin928** [hexschool/bootstrap_zh#17]
您好，
使用時發現英文版的文字排版中反轉排版 .blockquote-reverse 已經移掉了

Alignment改為使用 text-center 或 text-right 了

煩請確認 謝謝~

**Comment by Wcc723** [comment]
![image](https://user-images.githubusercontent.com/3422575/42487261-d13725cc-8432-11e8-81a6-9f902d622423.png)

4.1 中文版統一更新
