### ISSUE TITLE
CSS的Bootstrap CDN引用錯誤，無法運作。

### ISSUE THREAD

**Issue by dustinhsiao21** [hexschool/bootstrap_zh#2]
包括[首頁](http://bootstrap.hexschool.com/ )及[快速開始](http://bootstrap.hexschool.com/docs/4.0/getting-started/introduction/)的CSS的Bootstrap CDN皆異常：
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">`

應該修正為官網上的
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">`

**Comment by Wcc723** [comment]
感謝提醒，已修正
