### ISSUE TITLE
建議不要將文件中的 bookmark id 翻譯

### ISSUE THREAD

**Issue by doggy8088** [hexschool/bootstrap_zh#4]
我發現官網的網址：
http://getbootstrap.com/docs/4.0/components/button-group/#nesting

轉換到你們的網站後，網址的結構變得不一樣，因為 URL 中的 hash 被翻譯了：
http://bootstrap.hexschool.com/docs/4.0/components/button-group/#巢狀

關於 URL hash 這部分，建議不要翻譯，保持跟原文一樣較好，因為這樣比較難透過網址反查原文的所在位置。

**Comment by Wcc723** [comment]
保哥你好,

因為 Markdown 預設會將標題名稱改成 ID
標題翻譯成中文後，中文名稱也就是 ID
url 就必須跟著調整 
(但這段還沒有完全對應上，持續修正中)

**Comment by doggy8088** [comment]
@Wcc723 請問這個 Issue 有修掉嗎？怎麼被 Close 了？

**Comment by Wcc723** [comment]
@doggy8088 因為打算以中文版為主
所以會維持全中文的翻譯
不過你這次回文後還是有查一下怎麼解決此問題
預計在最近的改版修正連結的整合

**Comment by doggy8088** [comment]
@Wcc723 知道了，謝謝 👍

**Comment by Wcc723** [comment]
已改用中文標題、原文 id

**Comment by doggy8088** [comment]
@Wcc723 太棒了，終於可以正常用我自製的好用中英轉換工具了！ 👍 

如下動畫： 😄 
https://content.screencast.com/users/will.huang/folders/Snagit/media/944a9d92-c895-4b89-80c0-a9c45563c7d8/01.22.2018-11.48.gif

**Comment by Wcc723** [comment]
@doggy8088 這個有釋出嗎 >O<

**Comment by doggy8088** [comment]
老早就釋出了，沒什麼人在用，我一直有在更新 (吃自己的狗食) 😄 
https://github.com/miniasp/en-zh-bookmarklet
