### ISSUE TITLE
請保持英文名詞

### ISSUE THREAD

**Issue by tentenlee100** [hexschool/bootstrap_zh#5]
左邊的功能全部翻譯成中文後反而都看不太懂
可否比照內頁的title部分 ex: 文字排版 (Typography)
來做顯示，不然要一個一個點進去才知道再說甚麼

**Comment by Wcc723** [comment]
@tentenlee100 這個提議不錯
我測試看看中英混合狀態會不會造成跑版
如果沒有問題就會導入

**Comment by Wcc723** [comment]
元件、通用類別已經補上英文囉
